### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by mansooonuna** [mansooonuna/hh99-spring_post_lv3#1]
Lv2 과제에서 특정 기능을 수행하고 잘 동작했을 경우 성공했다는 메세지만 반환했었는데,

Lv3에서 `성공했다는 메시지, 상태코드`를 동시에 반환하기 위해 고민을 했었습니다.

페어의 코드를 보고 UserResponseDto로 세부화시켜 해당 메세지를 매개변수로 넘겨주면 반환값에 메세지와
지정해준 상태코드가 나오도록 수정했습니다.

```
 package com.sparta.spring_post.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor(staticName = "set")
public class UserResponseDto<D> {
    private String message;
    private int statusCode;

    public static <D> UserResponseDto<D> setSuccess(String message) {
        return UserResponseDto.set(message, 200);
    }

    public static <D> UserResponseDto<D> setFailed(String message) {
        return UserResponseDto.set(message, 400);
    }

}

```
나중에 좀 더 공부해보니 ResponseEntity 라는 것에 대해 더 알아보고 적용해야겠다고 생각했습니다.

**Comment by taetoo** [comment]
다솜님! 일단 여기까지 오시느라 수고 많으셨습니다 😊
우선 반환타입에 대한 고민을 많이 하신듯 한데, 아래 기술해주신 것과 같이 ResponseEntity를 통해 반환하는 방법이 일반적이긴 합니다.
제네릭을 이용해서 응답값을 넣어주셨는데 이 방법 또한 회사의 컨벤션(회사에서 정한 룰)에 따라 사용됩니다.
아래 레퍼런스 첨부해드렸으니 공부하시면 이해하시는데 도움이 되었으면 좋겠습니다.
추가로 HTTP 상태코드에 대한 레퍼런스도 공유해드렸으니, 참고 부탁드립니다. 🙇🏻

⭐️ **참고**
[ResponseEntity관련](https://www.baeldung.com/spring-response-entity)
[제네릭으로 Response 활용](https://veneas.tistory.com/entry/Java-%EC%9E%90%EB%B0%94-%EC%A0%9C%EB%84%A4%EB%A6%AD-API-Response-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0-Response-DTO) 
[HTTP status code 관련](https://stackoverflow.com/questions/39636795/http-status-code-4xx-vs-5xx)
